name: Terraform Dev Deploy
on: workflow_dispatch
jobs:
    plan:
        runs-on: self-hosted
        steps:
            - name: Check Repo
              uses: actions/checkout@v4
            - name: print
              run: echo index.html
